stages:
  download:
    cmd: python scripts/download_data.py
    deps:
      - scripts/download_data.py
    outs:
      - data/category_tree.csv
      - data/labeled_train.parquet
      - data/unlabeled_train.parquet