# Base model configuration
model:
  name: "cointegrated/rubert-tiny2"
  learning_rate: 2e-5
  dropout: 0.1
  freeze_encoder: true
  freeze_layers: 6  # 0=none, -1=all, N=first N layers

# Optimizer configuration
optimizer:
  name: "AdamW"
  learning_rate: 2e-5

# Scheduler configuration
scheduler:
  name: "ReduceLROnPlateau"
  mode: "min"
  factor: 0.5
  patience: 2
  monitor: "val_loss"
