# Base model configuration
model:
  name: "cointegrated/LaBSE-en-ru"
  learning_rate: 2e-5
  dropout: 0.1

# Optimizer configuration
optimizer:
  name: "AdamW"
  learning_rate: 2e-5

# Scheduler configuration
scheduler:
  name: "ReduceLROnPlateau"
  mode: "min"
  factor: 0.5
  patience: 2
  monitor: "val_loss"
